#!/usr/bin/env python3
import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / ".paddle.sandbox.env"
LOCAL_CONFIG_PATH = ROOT / "site" / "config.local.toml"
BASE_URL = "https://sandbox-api.paddle.com"


def load_env(path):
    values = {}
    if not path.exists():
        return values
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def paddle_request(method, path, api_key, payload=None):
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    request = urllib.request.Request(
        BASE_URL + path,
        data=data,
        method=method,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Accept": "application/json",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            body = response.read().decode("utf-8")
            return response.status, json.loads(body) if body else {}
    except urllib.error.HTTPError as error:
        body = error.read().decode("utf-8", errors="replace")
        try:
            parsed = json.loads(body)
        except Exception:
            parsed = {"raw": body}
        return error.code, parsed


def require_success(step, status, response):
    if status in (200, 201):
        return response.get("data") or response
    error = response.get("error", {}) if isinstance(response, dict) else {}
    detail = error.get("detail") or response
    raise RuntimeError(f"{step} failed ({status}): {detail}")


def write_local_config(price_id, client_token):
    LOCAL_CONFIG_PATH.write_text(
        "# Generated by scripts/setup-paddle-sandbox.py. Do not commit.\n"
        "[params]\n"
        "  paddleEnvironment = 'sandbox'\n"
        f"  paddlePriceID = '{price_id}'\n"
        f"  paddleClientToken = '{client_token}'\n"
    )


def main():
    env = load_env(ENV_PATH)
    existing_price_id = env.get("PADDLE_SANDBOX_PRICE_ID")
    existing_client_token = env.get("PADDLE_SANDBOX_CLIENT_TOKEN")
    if existing_price_id and existing_client_token:
        write_local_config(existing_price_id, existing_client_token)
        print(json.dumps({"mode": "existing", "price_id": existing_price_id, "client_token_prefix": existing_client_token[:6] + "…"}, ensure_ascii=False, indent=2))
        return

    api_key = env.get("PADDLE_API_KEY")
    if not api_key:
        raise RuntimeError("Missing .paddle.sandbox.env with PADDLE_API_KEY. Copy .paddle.sandbox.env.example first.")
    if not api_key.startswith("pdl_sdbx_"):
        raise RuntimeError("PADDLE_API_KEY must be a sandbox key that starts with pdl_sdbx_.")

    status, product_response = paddle_request("POST", "/products", api_key, {
        "name": "CleanMac Sandbox",
        "description": "Sandbox catalog item for CleanMac local checkout testing.",
        "tax_category": "standard",
    })
    product = require_success("create product", status, product_response)

    status, price_response = paddle_request("POST", "/prices", api_key, {
        "description": "CleanMac sandbox one-time license",
        "product_id": product["id"],
        "unit_price": {"amount": "1000", "currency_code": "CNY"},
        "billing_cycle": None,
        "quantity": {"minimum": 1, "maximum": 1},
    })
    price = require_success("create price", status, price_response)

    status, token_response = paddle_request("POST", "/client-tokens", api_key, {
        "name": "CleanMac local sandbox checkout",
        "description": "Client-side token for local CleanMac Paddle sandbox checkout testing.",
    })
    token = require_success("create client token", status, token_response)
    client_token = token.get("token")
    if not client_token:
        raise RuntimeError("create client token succeeded but response did not include token")

    write_local_config(price["id"], client_token)
    print(json.dumps({
        "mode": "created",
        "product_id": product["id"],
        "price_id": price["id"],
        "client_token_prefix": client_token[:6] + "…",
        "local_config": str(LOCAL_CONFIG_PATH.relative_to(ROOT)),
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    try:
        main()
    except Exception as error:
        print(f"ERROR: {error}", file=sys.stderr)
        sys.exit(1)
